import { AmalaSpot } from "./types";

export const aiSuggestedSpots = [
   {
      id: "ai1",
      name: "Eko Bridge Under Amala",
      address: "Under Eko Bridge, Lagos Island",
      source: "Social Media Scraping",
      confidence: 0.75,
      reason:
         "Multiple social media mentions and photos tagged at this location",
   },
   {
      id: "ai2",
      name: "Night Market Amala Stand",
      address: "Computer Village Night Market, Ikeja",
      source: "Location Analysis",
      confidence: 0.68,
      reason: "High foot traffic area with food vendor patterns detected",
   },
];

export const amalaSpots: AmalaSpot[] = [
   {
      id: "1",
      name: "Mama Tola's Original Amala",
      address: "15 Idumagbo Avenue, Lagos Island",
      coordinates: [3.3792, 6.4541],
      description:
         "The legendary Mama Tola serves the most authentic amala in Lagos. Been running this spot for over 30 years with the same secret recipe.",
      photos: ["/api/placeholder/400/300", "/api/placeholder/400/300"],
      rating: 4.8,
      reviewCount: 127,
      verified: true,
      addedBy: "user1",
      dateAdded: "2024-01-15",
      tags: ["traditional", "authentic", "family-owned"],
      priceRange: "$$",
      openHours: "8AM - 8PM",
      phone: "+234 901 234 5678",
      specialties: ["Amala Isu", "Ewedu", "Gbegiri", "Assorted meat"],
   },
   {
      id: "2",
      name: "Bukky's Kitchen",
      address: "23 Allen Avenue, Ikeja",
      coordinates: [3.3566, 6.6018],
      description:
         "Modern amala joint with a clean environment. Popular with office workers and young professionals.",
      photos: ["/api/placeholder/400/300"],
      rating: 4.5,
      reviewCount: 89,
      verified: true,
      addedBy: "user2",
      dateAdded: "2024-02-03",
      tags: ["modern", "clean", "professional"],
      priceRange: "$$$",
      openHours: "11AM - 9PM",
      phone: "+234 802 345 6789",
      specialties: ["Amala Lafun", "Okra soup", "Efo riro"],
   },
   {
      id: "3",
      name: "Iya Agba Amala Spot",
      address: "7 Ojuelegba Road, Surulere",
      coordinates: [3.3515, 6.5075],
      description:
         "No-frills roadside amala that locals swear by. Cash only, but worth every naira.",
      photos: ["/api/placeholder/400/300"],
      rating: 4.6,
      reviewCount: 203,
      verified: true,
      addedBy: "user3",
      dateAdded: "2024-01-28",
      tags: ["roadside", "local-favorite", "cash-only"],
      priceRange: "$",
      openHours: "7AM - 7PM",
      specialties: ["Amala Isu", "Ewedu", "Fresh fish", "Goat meat"],
   },
   {
      id: "4",
      name: "Sunset Amala Palace",
      address: "12 Victoria Island Extension",
      coordinates: [3.4298, 6.4281],
      description:
         "Upscale amala restaurant with AC and proper seating. Perfect for business lunches.",
      photos: ["/api/placeholder/400/300", "/api/placeholder/400/300"],
      rating: 4.3,
      reviewCount: 76,
      verified: true,
      addedBy: "user4",
      dateAdded: "2024-02-12",
      tags: ["upscale", "ac", "business"],
      priceRange: "$$$",
      openHours: "10AM - 10PM",
      phone: "+234 703 456 7890",
      specialties: ["Amala Lafun", "Seafood okra", "Peppered snail"],
   },
   {
      id: "5",
      name: "Yaba Student Special",
      address: "45 Herbert Macaulay Way, Yaba",
      coordinates: [3.3728, 6.5158],
      description:
         "Budget-friendly amala joint popular with university students. Large portions, small prices.",
      photos: ["/api/placeholder/400/300"],
      rating: 4.2,
      reviewCount: 156,
      verified: false,
      addedBy: "user5",
      dateAdded: "2024-02-20",
      tags: ["student-friendly", "budget", "large-portions"],
      priceRange: "$",
      openHours: "9AM - 8PM",
      specialties: ["Amala Isu", "Ewedu", "Fried meat", "Moin moin"],
   },
   {
      id: "6",
      name: "Aunty Kemi's Kitchen",
      address: "8 Adeniran Ogunsanya Street, Surulere",
      coordinates: [3.3557, 6.5044],
      description:
         "Home-style cooking in a warm, welcoming atmosphere. Feel like you're eating at your grandmother's.",
      photos: ["/api/placeholder/400/300"],
      rating: 4.7,
      reviewCount: 94,
      verified: true,
      addedBy: "user6",
      dateAdded: "2024-01-10",
      tags: ["homestyle", "welcoming", "family"],
      priceRange: "$$",
      openHours: "8AM - 7PM",
      phone: "+234 805 567 8901",
      specialties: ["Amala Lafun", "Gbegiri", "Efo", "Cow leg"],
   },
   {
      id: "7",
      name: "Lagos Island Heritage",
      address: "3 Broad Street, Lagos Island",
      coordinates: [3.3952, 6.4541],
      description:
         "Historic amala spot that's been serving the island community for decades. Traditional recipes passed down through generations.",
      photos: ["/api/placeholder/400/300", "/api/placeholder/400/300"],
      rating: 4.9,
      reviewCount: 312,
      verified: true,
      addedBy: "user7",
      dateAdded: "2024-01-05",
      tags: ["historic", "traditional", "heritage"],
      priceRange: "$$",
      openHours: "7AM - 8PM",
      phone: "+234 906 678 9012",
      specialties: ["Amala Isu", "Native soup", "Dried fish", "Ponmo"],
   },
   {
      id: "8",
      name: "Mainland Express",
      address: "29 Ikorodu Road, Maryland",
      coordinates: [3.3669, 6.5707],
      description:
         "Quick service amala joint for people on the go. Drive-through available!",
      photos: ["/api/placeholder/400/300"],
      rating: 4.1,
      reviewCount: 67,
      verified: false,
      addedBy: "user8",
      dateAdded: "2024-02-25",
      tags: ["quick-service", "drive-through", "modern"],
      priceRange: "$$",
      openHours: "24/7",
      phone: "+234 807 789 0123",
      specialties: ["Amala takeaway", "Packaged soups", "Quick bites"],
   },
   {
      id: "9",
      name: "Festac Community Kitchen",
      address: "16 2nd Avenue, Festac Town",
      coordinates: [3.2792, 6.4637],
      description:
         "Community-centered amala spot that brings neighbors together over great food.",
      photos: ["/api/placeholder/400/300"],
      rating: 4.4,
      reviewCount: 128,
      verified: true,
      addedBy: "user9",
      dateAdded: "2024-02-08",
      tags: ["community", "neighborhood", "social"],
      priceRange: "$$",
      openHours: "9AM - 9PM",
      specialties: ["Amala Lafun", "Vegetable soup", "Fresh meat"],
   },
   {
      id: "10",
      name: "Lekki Phase 1 Deluxe",
      address: "5 Admiralty Way, Lekki Phase 1",
      coordinates: [3.4716, 6.4474],
      description:
         "Premium amala experience in upscale Lekki. Beautiful ambiance with authentic taste.",
      photos: ["/api/placeholder/400/300", "/api/placeholder/400/300"],
      rating: 4.6,
      reviewCount: 201,
      verified: true,
      addedBy: "user10",
      dateAdded: "2024-01-22",
      tags: ["premium", "lekki", "ambiance"],
      priceRange: "$$$",
      openHours: "11AM - 11PM",
      phone: "+234 908 890 1234",
      specialties: ["Gourmet Amala", "Premium soups", "Wine pairing"],
   },
   {
      id: "11",
      name: "Agege Authentic Corner",
      address: "12 Old Abeokuta Road, Agege",
      coordinates: [3.3276, 6.6342],
      description:
         "Hidden gem in Agege serving some of the most authentic amala you'll find anywhere.",
      photos: ["/api/placeholder/400/300"],
      rating: 4.8,
      reviewCount: 89,
      verified: false,
      addedBy: "user11",
      dateAdded: "2024-03-01",
      tags: ["hidden-gem", "authentic", "local"],
      priceRange: "$",
      openHours: "8AM - 6PM",
      specialties: ["Traditional Amala", "Local spices", "Farm fresh"],
   },
   {
      id: "12",
      name: "Apapa Harbor View",
      address: "22 Wharf Road, Apapa",
      coordinates: [3.3569, 6.4395],
      description:
         "Popular with dock workers and seafarers. Hearty portions perfect after a long day's work.",
      photos: ["/api/placeholder/400/300"],
      rating: 4.3,
      reviewCount: 145,
      verified: true,
      addedBy: "user12",
      dateAdded: "2024-02-15",
      tags: ["harbor", "workers", "hearty"],
      priceRange: "$$",
      openHours: "6AM - 9PM",
      phone: "+234 909 901 2345",
      specialties: ["Amala Isu", "Sea food soup", "Energy portions"],
   },
];
